### ISSUE TITLE
Elevation motor pointing gain

### ISSUE THREAD

**Issue by sethhillbrand** [BlastTNG/flight#39]
There is a pointing gain term in the elevation motor controller command_data.  Evaluate whether we need this term and if not, remove from commanding.

**Comment by fissel** [comment]
So we definitely do want to keep the pointing gain term for the elevation motor.  This is used when mcp is in a goto position mode (see get_elev_vel() in motors.c).  In this case the requested velocity amplitude is the square root of the distance from the target elevation times the pointing gain.  So increasing the pointing gain will increase how fast we approach our target elevation (in pointing mode).  Set it too high though and we will keep overshooting the target elevation.
