### ISSUE TITLE
Running cow (on a Mac) causes the blastcmd daemon to segfault

### ISSUE THREAD

**Issue by fissel** [BlastTNG/flight#52]
Connecting to 128.91.40.193 with cow with a Mac causes blastcmd daemon to segfault on the flight computer.
[blastcmd_daemon_output.txt](https://github.com/BlastTNG/flight/files/58572/blastcmd_daemon_output.txt)

**Comment by sethhillbrand** [comment]
Fixed in https://github.com/BlastTNG/flight/commit/acf7f5af1fdc9daf5e920032ea94b4fc2a843d28
