### ISSUE TITLE
Occasional gyro initialization problems?

### ISSUE THREAD

**Issue by fissel** [BlastTNG/flight#53]
Occasionally mcp seems to not initialize the gyro readout properly.  I've noticed it 2 times (out of more than 10 mcp restarts) in one night.  All the individual gyro and combined gyro TOD are non-zero but flat.  Other fast channels (EL, MC_EL_I_READ) appear to be read out as normal.  Note in the example below that the derived field ERROR_AZ (AZ_GY-VEL_REQ_AZ) has no noise, which makes me think this is an mcp gyro communications problem rather than a defricher problem.

<img width="1094" alt="screenshot 2015-12-13 00 43 45" src="https://cloud.githubusercontent.com/assets/15033087/11765722/ad804040-a132-11e5-9ff7-781704288f8e.png">

From the log mcp claims it has initialized the gyro communications:

> 0346-12-13 05:18:55.476 > Schedu: dsp1760.c:326 (initialize_dsp1760_interface):Initialized gyroscope interface
> Then a few lines later:
> = 0346-12-13 05:18:55.613 = Schedu: dsp1760.c:263 (dsp1760_process_data):Expected Sequence 1 but received 100 from gyro 1

I didn't see any other warnings or error messages from dsp1760.c.  

Communication with the gyros can be recovered by restarting mcp.

**Comment by sethhillbrand** [comment]
Attempted to re-create.  Observed in previous build.  After commit cdcdb8c47a89e6d34bec468ed30830ee2b7556a9 the issue has not been observed in 50 restarts.  If seen again, we'll re-open.
